# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/mysteriumnetwork/payments"
  version = "0.0.10"

[[constraint]]
  name = "github.com/chzyer/readline"
  revision = "2972be24d48e78746da79ba8e24e8b488c9880de"

[[constraint]]
  name = "github.com/cihub/seelog"
  version = "2.6.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=1.8.23"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.4.0"

[[constraint]]
  name = "github.com/oschwald/geoip2-golang"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.1.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/mysteriumnetwork/go-openvpn"
  version = "0.0.13"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false

  [[prune.project]]
    name = "github.com/mysteriumnetwork/go-openvpn"
    unused-packages = false

  [[prune.project]]
    name = "github.com/mysteriumnetwork/payments"
    unused-packages = false


[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/asdine/storm"
  version = "2.2.1"

[[override]]
  name = "go.etcd.io/bbolt"
  version = "1.3.2"

[[constraint]]
  name = "github.com/asaskevich/EventBus"
  revision = "d46933a94f05c6657d7b923fcf5ac563ee37ec79"

[[constraint]]
  revision = "5ec88494b814a16a2a5fa7f2cfb4b94016ac5fac"
  name = "golang.zx2c4.com/wireguard/wgctrl"

[[constraint]]
  name = "github.com/mysteriumnetwork/wireguard-go"
  revision = "625d21fc42f3eb8912bb031763c917c7fed7372f"

[[constraint]]
  name = "github.com/jackpal/gateway"
  version = "1.0.5"

[[constraint]]
  revision = "f6122f5b2fbd92ace9b2819f0be4148be5690a1f"
  name = "github.com/songgao/water"

[[constraint]]
  version = "1.3.0"
  name = "github.com/gin-contrib/cors"

[[constraint]]
  version = "1.4.0"
  name = "github.com/gin-gonic/gin"

[[constraint]]
  version = "=0.0.1"
  name = "github.com/mysteriumnetwork/go-dvpn-web"
