version: '3'
services:

  myst-provider:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    depends_on:
      - broker
      - discovery
      - ipify
    cap_add:
      - NET_ADMIN
    expose:
      - 1194
      - 4050
    volumes:
      - ../../e2e/myst-provider:/var/lib/mysterium-node
    command: >
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --location.country=e2e-land
      --experiment-identity-check
      --localnet
      --broker-address=broker
      --discovery.address=http://discovery/v1
      --ether.client.rpc=http://geth:8545
      --keystore.lightweight
      service openvpn,noop,wireguard
      --agreed-terms-and-conditions
      --identity=0xd1a23227bd5ad77f36ba62badcb78a410a1db6c5
      --identity.passphrase=localprovider
      --openvpn.port=3000

  myst-consumer:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    depends_on:
      - broker
      - discovery
      - ipify
    cap_add:
      - NET_ADMIN
    expose:
      - 4050
    command: >
      --ip-detector=http://ipify:3000/?format=json
      --experiment-identity-check
      --localnet
      --discovery.address=http://discovery/v1
      --ether.client.rpc=http://geth:8545
      --keystore.lightweight
      daemon

  #'external' IP detection
  ipify:
    image: owlab/ipify
    expose:
    - 3000
